enyo.depends(
	"css/",
	"ButtonDecorator.js",
	"ButtonBase.js",
	"Button.js",
	"Checkbox.js",
	"Input.js",
	"InputDecorator.js",
	"ProgressBar.js",
	"ProgressText.js",
	"RichText.js",
	"TextArea.js",
	"ToggleButton.js",
	"ViewSelector.js"
);
