enyo.depends(
	"css/",
	"ButtonDecorator.js",
	"Button.js",
	"RadioButton.js",
	"Checkbox.js",
	"Icon.js",
	"IconButton.js",
	"Input.js",
	"InputDecorator.js",
	"Popup.js",
	"ProgressBar.js",
	"ProgressText.js",
	"RichText.js",
	"Slider.js",
	"TextArea.js",
	"ToggleButton.js",
	"ViewSelectButton.js"
);
